/* this file has been autogenerated by vtkNodeJsWrap */
/* editing this might proof futile */

#ifndef NATIVE_EXTENSION_VTK_VTKCELLLINKSWRAP_H
#define NATIVE_EXTENSION_VTK_VTKCELLLINKSWRAP_H

#include <nan.h>

#include <vtkSmartPointer.h>
#include <vtkCellLinks.h>

#include "vtkAbstractCellLinksWrap.h"
#include "../../plus/plus.h"

class VtkCellLinksWrap : public VtkAbstractCellLinksWrap
{
	public:
		using Nan::ObjectWrap::Wrap;
		static void Init(v8::Local<v8::Object> exports);
		static void InitPtpl();
		static void ConstructorGetter(
			v8::Local<v8::String> property,
			const Nan::PropertyCallbackInfo<v8::Value>& info);

		VtkCellLinksWrap(vtkSmartPointer<vtkCellLinks>);
		VtkCellLinksWrap();
		~VtkCellLinksWrap( );
		static Nan::Persistent<v8::FunctionTemplate> ptpl;

	private:
		static void New(const Nan::FunctionCallbackInfo<v8::Value>& info);

		static void BuildLinks(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void DeepCopy(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void GetClassName(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void Initialize(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void IsA(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void NewInstance(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void Reset(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SafeDownCast(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void Squeeze(const Nan::FunctionCallbackInfo<v8::Value>& info);

#ifdef VTK_NODE_PLUS_VTKCELLLINKSWRAP_CLASSDEF
		VTK_NODE_PLUS_VTKCELLLINKSWRAP_CLASSDEF
#endif
};

#endif
