/* this file has been autogenerated by vtkNodeJsWrap */
/* editing this might proof futile */

#ifndef NATIVE_EXTENSION_VTK_VTKMULTITHRESHOLDWRAP_H
#define NATIVE_EXTENSION_VTK_VTKMULTITHRESHOLDWRAP_H

#include <nan.h>

#include <vtkSmartPointer.h>
#include <vtkMultiThreshold.h>

#include "vtkMultiBlockDataSetAlgorithmWrap.h"
#include "../../plus/plus.h"

class VtkMultiThresholdWrap : public VtkMultiBlockDataSetAlgorithmWrap
{
	public:
		using Nan::ObjectWrap::Wrap;
		static void Init(v8::Local<v8::Object> exports);
		static void InitPtpl();
		static void ConstructorGetter(
			v8::Local<v8::String> property,
			const Nan::PropertyCallbackInfo<v8::Value>& info);

		VtkMultiThresholdWrap(vtkSmartPointer<vtkMultiThreshold>);
		VtkMultiThresholdWrap();
		~VtkMultiThresholdWrap( );
		static Nan::Persistent<v8::FunctionTemplate> ptpl;

	private:
		static void New(const Nan::FunctionCallbackInfo<v8::Value>& info);

		static void AddBandpassIntervalSet(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void AddHighpassIntervalSet(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void AddIntervalSet(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void AddLowpassIntervalSet(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void AddNotchIntervalSet(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void GetClassName(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void IsA(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void NewInstance(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void OutputSet(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void Reset(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SafeDownCast(const Nan::FunctionCallbackInfo<v8::Value>& info);

#ifdef VTK_NODE_PLUS_VTKMULTITHRESHOLDWRAP_CLASSDEF
		VTK_NODE_PLUS_VTKMULTITHRESHOLDWRAP_CLASSDEF
#endif
};

#endif
