/* this file has been autogenerated by vtkNodeJsWrap */
/* editing this might proof futile */

#ifndef NATIVE_EXTENSION_VTK_VTKEXTRACTHIERARCHICALBINSWRAP_H
#define NATIVE_EXTENSION_VTK_VTKEXTRACTHIERARCHICALBINSWRAP_H

#include <nan.h>

#include <vtkSmartPointer.h>
#include <vtkExtractHierarchicalBins.h>

#include "vtkPointCloudFilterWrap.h"
#include "../../plus/plus.h"

class VtkExtractHierarchicalBinsWrap : public VtkPointCloudFilterWrap
{
	public:
		using Nan::ObjectWrap::Wrap;
		static void Init(v8::Local<v8::Object> exports);
		static void InitPtpl();
		static void ConstructorGetter(
			v8::Local<v8::String> property,
			const Nan::PropertyCallbackInfo<v8::Value>& info);

		VtkExtractHierarchicalBinsWrap(vtkSmartPointer<vtkExtractHierarchicalBins>);
		VtkExtractHierarchicalBinsWrap();
		~VtkExtractHierarchicalBinsWrap( );
		static Nan::Persistent<v8::FunctionTemplate> ptpl;

	private:
		static void New(const Nan::FunctionCallbackInfo<v8::Value>& info);

		static void GetBin(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void GetBinningFilter(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void GetLevel(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void NewInstance(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SafeDownCast(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SetBin(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SetBinningFilter(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SetLevel(const Nan::FunctionCallbackInfo<v8::Value>& info);

#ifdef VTK_NODE_PLUS_VTKEXTRACTHIERARCHICALBINSWRAP_CLASSDEF
		VTK_NODE_PLUS_VTKEXTRACTHIERARCHICALBINSWRAP_CLASSDEF
#endif
};

#endif
