/* this file has been autogenerated by vtkNodeJsWrap */
/* editing this might proof futile */

#ifndef NATIVE_EXTENSION_VTK_VTKFORCETIMEWRAP_H
#define NATIVE_EXTENSION_VTK_VTKFORCETIMEWRAP_H

#include <nan.h>

#include <vtkSmartPointer.h>
#include <vtkForceTime.h>

#include "vtkPassInputTypeAlgorithmWrap.h"
#include "../../plus/plus.h"

class VtkForceTimeWrap : public VtkPassInputTypeAlgorithmWrap
{
	public:
		using Nan::ObjectWrap::Wrap;
		static void Init(v8::Local<v8::Object> exports);
		static void InitPtpl();
		static void ConstructorGetter(
			v8::Local<v8::String> property,
			const Nan::PropertyCallbackInfo<v8::Value>& info);

		VtkForceTimeWrap(vtkSmartPointer<vtkForceTime>);
		VtkForceTimeWrap();
		~VtkForceTimeWrap( );
		static Nan::Persistent<v8::FunctionTemplate> ptpl;

	private:
		static void New(const Nan::FunctionCallbackInfo<v8::Value>& info);

		static void GetForcedTime(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void GetIgnorePipelineTime(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void IgnorePipelineTimeOff(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void IgnorePipelineTimeOn(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void NewInstance(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SafeDownCast(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SetForcedTime(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SetIgnorePipelineTime(const Nan::FunctionCallbackInfo<v8::Value>& info);

#ifdef VTK_NODE_PLUS_VTKFORCETIMEWRAP_CLASSDEF
		VTK_NODE_PLUS_VTKFORCETIMEWRAP_CLASSDEF
#endif
};

#endif
