/* this file has been autogenerated by vtkNodeJsWrap */
/* editing this might proof futile */

#ifndef NATIVE_EXTENSION_VTK_VTKSURFACERECONSTRUCTIONFILTERWRAP_H
#define NATIVE_EXTENSION_VTK_VTKSURFACERECONSTRUCTIONFILTERWRAP_H

#include <nan.h>

#include <vtkSmartPointer.h>
#include <vtkSurfaceReconstructionFilter.h>

#include "vtkImageAlgorithmWrap.h"
#include "../../plus/plus.h"

class VtkSurfaceReconstructionFilterWrap : public VtkImageAlgorithmWrap
{
	public:
		using Nan::ObjectWrap::Wrap;
		static void Init(v8::Local<v8::Object> exports);
		static void InitPtpl();
		static void ConstructorGetter(
			v8::Local<v8::String> property,
			const Nan::PropertyCallbackInfo<v8::Value>& info);

		VtkSurfaceReconstructionFilterWrap(vtkSmartPointer<vtkSurfaceReconstructionFilter>);
		VtkSurfaceReconstructionFilterWrap();
		~VtkSurfaceReconstructionFilterWrap( );
		static Nan::Persistent<v8::FunctionTemplate> ptpl;

	private:
		static void New(const Nan::FunctionCallbackInfo<v8::Value>& info);

		static void GetNeighborhoodSize(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void GetSampleSpacing(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void NewInstance(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SafeDownCast(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SetNeighborhoodSize(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SetSampleSpacing(const Nan::FunctionCallbackInfo<v8::Value>& info);

#ifdef VTK_NODE_PLUS_VTKSURFACERECONSTRUCTIONFILTERWRAP_CLASSDEF
		VTK_NODE_PLUS_VTKSURFACERECONSTRUCTIONFILTERWRAP_CLASSDEF
#endif
};

#endif
