/* this file has been autogenerated by vtkNodeJsWrap */
/* editing this might proof futile */

#define VTK_WRAPPING_CXX
#define VTK_STREAMS_FWD_ONLY
#include <nan.h>


#include "vtkChartWrap.h"
#include "vtkChartParallelCoordinatesWrap.h"
#include "vtkObjectWrap.h"
#include "vtkStringArrayWrap.h"
#include "vtkAxisWrap.h"
#include "vtkPlotParallelCoordinatesWrap.h"

using namespace v8;

extern Nan::Persistent<v8::Object> vtkNodeJsNoWrap;
Nan::Persistent<v8::Function> VtkChartParallelCoordinatesWrap::constructor;
Nan::Persistent<v8::FunctionTemplate> VtkChartParallelCoordinatesWrap::ptpl;

VtkChartParallelCoordinatesWrap::VtkChartParallelCoordinatesWrap()
{ }

VtkChartParallelCoordinatesWrap::VtkChartParallelCoordinatesWrap(vtkSmartPointer<vtkChartParallelCoordinates> _native)
{ native = _native; }

VtkChartParallelCoordinatesWrap::~VtkChartParallelCoordinatesWrap()
{ }

void VtkChartParallelCoordinatesWrap::Init(v8::Local<v8::Object> exports)
{
	if (!constructor.IsEmpty()) return;
	Nan::HandleScope scope;

	v8::Local<v8::FunctionTemplate> tpl = Nan::New<v8::FunctionTemplate>(New);
	VtkChartWrap::Init( exports );
	tpl->Inherit(Nan::New<FunctionTemplate>(VtkChartWrap::ptpl));

	tpl->SetClassName(Nan::New("VtkChartParallelCoordinatesWrap").ToLocalChecked());
	tpl->InstanceTemplate()->SetInternalFieldCount(1);
	InitTpl(tpl);

	constructor.Reset( tpl->GetFunction() );
	ptpl.Reset( tpl );

	exports->Set(Nan::New("vtkChartParallelCoordinates").ToLocalChecked(),tpl->GetFunction());
	exports->Set(Nan::New("ChartParallelCoordinates").ToLocalChecked(),tpl->GetFunction());
}

void VtkChartParallelCoordinatesWrap::InitTpl(v8::Local<v8::FunctionTemplate> tpl)
{
	Nan::SetPrototypeMethod(tpl, "GetAxis", GetAxis);
	Nan::SetPrototypeMethod(tpl, "getAxis", GetAxis);

	Nan::SetPrototypeMethod(tpl, "GetClassName", GetClassName);
	Nan::SetPrototypeMethod(tpl, "getClassName", GetClassName);

	Nan::SetPrototypeMethod(tpl, "GetVisibleColumns", GetVisibleColumns);
	Nan::SetPrototypeMethod(tpl, "getVisibleColumns", GetVisibleColumns);

	Nan::SetPrototypeMethod(tpl, "IsA", IsA);
	Nan::SetPrototypeMethod(tpl, "isA", IsA);

	Nan::SetPrototypeMethod(tpl, "NewInstance", NewInstance);
	Nan::SetPrototypeMethod(tpl, "newInstance", NewInstance);

	Nan::SetPrototypeMethod(tpl, "RecalculateBounds", RecalculateBounds);
	Nan::SetPrototypeMethod(tpl, "recalculateBounds", RecalculateBounds);

	Nan::SetPrototypeMethod(tpl, "SafeDownCast", SafeDownCast);
	Nan::SetPrototypeMethod(tpl, "safeDownCast", SafeDownCast);

	Nan::SetPrototypeMethod(tpl, "SetPlot", SetPlot);
	Nan::SetPrototypeMethod(tpl, "setPlot", SetPlot);

	Nan::SetPrototypeMethod(tpl, "Update", Update);
	Nan::SetPrototypeMethod(tpl, "update", Update);

}

void VtkChartParallelCoordinatesWrap::New(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	if(!info.IsConstructCall())
	{
		Nan::ThrowError("Constructor not called in a construct call.");
		return;
	}

	if(info.Length() == 0)
	{
		vtkSmartPointer<vtkChartParallelCoordinates> native = vtkSmartPointer<vtkChartParallelCoordinates>::New();
		VtkChartParallelCoordinatesWrap* obj = new VtkChartParallelCoordinatesWrap(native);		obj->Wrap(info.This());
	}
	else
	{
		Nan::Utf8String s(info[0]);
		if(info[0]->ToObject() != vtkNodeJsNoWrap )
			Nan::ThrowError("Parameter Error");
	}

	info.GetReturnValue().Set(info.This());
}

void VtkChartParallelCoordinatesWrap::GetAxis(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkChartParallelCoordinatesWrap *wrapper = ObjectWrap::Unwrap<VtkChartParallelCoordinatesWrap>(info.Holder());
	vtkChartParallelCoordinates *native = (vtkChartParallelCoordinates *)wrapper->native.GetPointer();
	if(info.Length() > 0 && info[0]->IsInt32())
	{
		vtkAxis * r;
		if(info.Length() != 1)
		{
			Nan::ThrowError("Too many parameters.");
			return;
		}
		r = native->GetAxis(
			info[0]->Int32Value()
		);
		v8::Local<v8::Value> argv[1] =
			{ Nan::New(vtkNodeJsNoWrap) };
		v8::Local<v8::Function> cons =
			Nan::New<v8::Function>(VtkAxisWrap::constructor);
		v8::Local<v8::Object> wo = cons->NewInstance(1, argv);
		VtkAxisWrap *w = new VtkAxisWrap();
		w->native.TakeReference(r);
		w->Wrap(wo);
		info.GetReturnValue().Set(wo);
		return;
	}
	Nan::ThrowError("Parameter mismatch");
}

void VtkChartParallelCoordinatesWrap::GetClassName(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkChartParallelCoordinatesWrap *wrapper = ObjectWrap::Unwrap<VtkChartParallelCoordinatesWrap>(info.Holder());
	vtkChartParallelCoordinates *native = (vtkChartParallelCoordinates *)wrapper->native.GetPointer();
	char const * r;
	if(info.Length() != 0)
	{
		Nan::ThrowError("Too many parameters.");
		return;
	}
	r = native->GetClassName();
	info.GetReturnValue().Set(Nan::New(r).ToLocalChecked());
}

void VtkChartParallelCoordinatesWrap::GetVisibleColumns(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkChartParallelCoordinatesWrap *wrapper = ObjectWrap::Unwrap<VtkChartParallelCoordinatesWrap>(info.Holder());
	vtkChartParallelCoordinates *native = (vtkChartParallelCoordinates *)wrapper->native.GetPointer();
	vtkStringArray * r;
	if(info.Length() != 0)
	{
		Nan::ThrowError("Too many parameters.");
		return;
	}
	r = native->GetVisibleColumns();
	v8::Local<v8::Value> argv[1] =
		{ Nan::New(vtkNodeJsNoWrap) };
	v8::Local<v8::Function> cons =
		Nan::New<v8::Function>(VtkStringArrayWrap::constructor);
	v8::Local<v8::Object> wo = cons->NewInstance(1, argv);
	VtkStringArrayWrap *w = new VtkStringArrayWrap();
	w->native.TakeReference(r);
	w->Wrap(wo);
	info.GetReturnValue().Set(wo);
}

void VtkChartParallelCoordinatesWrap::IsA(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkChartParallelCoordinatesWrap *wrapper = ObjectWrap::Unwrap<VtkChartParallelCoordinatesWrap>(info.Holder());
	vtkChartParallelCoordinates *native = (vtkChartParallelCoordinates *)wrapper->native.GetPointer();
	if(info.Length() > 0 && info[0]->IsInt32())
	{
		Nan::Utf8String a0(info[0]);
		int r;
		if(info.Length() != 1)
		{
			Nan::ThrowError("Too many parameters.");
			return;
		}
		r = native->IsA(
			*a0
		);
		info.GetReturnValue().Set(Nan::New(r));
		return;
	}
	Nan::ThrowError("Parameter mismatch");
}

void VtkChartParallelCoordinatesWrap::NewInstance(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkChartParallelCoordinatesWrap *wrapper = ObjectWrap::Unwrap<VtkChartParallelCoordinatesWrap>(info.Holder());
	vtkChartParallelCoordinates *native = (vtkChartParallelCoordinates *)wrapper->native.GetPointer();
	vtkChartParallelCoordinates * r;
	if(info.Length() != 0)
	{
		Nan::ThrowError("Too many parameters.");
		return;
	}
	r = native->NewInstance();
	v8::Local<v8::Value> argv[1] =
		{ Nan::New(vtkNodeJsNoWrap) };
	v8::Local<v8::Function> cons =
		Nan::New<v8::Function>(VtkChartParallelCoordinatesWrap::constructor);
	v8::Local<v8::Object> wo = cons->NewInstance(1, argv);
	VtkChartParallelCoordinatesWrap *w = new VtkChartParallelCoordinatesWrap();
	w->native.TakeReference(r);
	w->Wrap(wo);
	info.GetReturnValue().Set(wo);
}

void VtkChartParallelCoordinatesWrap::RecalculateBounds(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkChartParallelCoordinatesWrap *wrapper = ObjectWrap::Unwrap<VtkChartParallelCoordinatesWrap>(info.Holder());
	vtkChartParallelCoordinates *native = (vtkChartParallelCoordinates *)wrapper->native.GetPointer();
	if(info.Length() != 0)
	{
		Nan::ThrowError("Too many parameters.");
		return;
	}
	native->RecalculateBounds();
}

void VtkChartParallelCoordinatesWrap::SafeDownCast(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkChartParallelCoordinatesWrap *wrapper = ObjectWrap::Unwrap<VtkChartParallelCoordinatesWrap>(info.Holder());
	vtkChartParallelCoordinates *native = (vtkChartParallelCoordinates *)wrapper->native.GetPointer();
	if(info.Length() > 0 && info[0]->IsObject())
	{
		VtkObjectWrap *a0 = ObjectWrap::Unwrap<VtkObjectWrap>(info[0]->ToObject());
		vtkChartParallelCoordinates * r;
		if(info.Length() != 1)
		{
			Nan::ThrowError("Too many parameters.");
			return;
		}
		r = native->SafeDownCast(
			(vtkObject *) a0->native.GetPointer()
		);
		v8::Local<v8::Value> argv[1] =
			{ Nan::New(vtkNodeJsNoWrap) };
		v8::Local<v8::Function> cons =
			Nan::New<v8::Function>(VtkChartParallelCoordinatesWrap::constructor);
		v8::Local<v8::Object> wo = cons->NewInstance(1, argv);
		VtkChartParallelCoordinatesWrap *w = new VtkChartParallelCoordinatesWrap();
		w->native.TakeReference(r);
		w->Wrap(wo);
		info.GetReturnValue().Set(wo);
		return;
	}
	Nan::ThrowError("Parameter mismatch");
}

void VtkChartParallelCoordinatesWrap::SetPlot(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkChartParallelCoordinatesWrap *wrapper = ObjectWrap::Unwrap<VtkChartParallelCoordinatesWrap>(info.Holder());
	vtkChartParallelCoordinates *native = (vtkChartParallelCoordinates *)wrapper->native.GetPointer();
	if(info.Length() > 0 && info[0]->IsObject())
	{
		VtkPlotParallelCoordinatesWrap *a0 = ObjectWrap::Unwrap<VtkPlotParallelCoordinatesWrap>(info[0]->ToObject());
		if(info.Length() != 1)
		{
			Nan::ThrowError("Too many parameters.");
			return;
		}
		native->SetPlot(
			(vtkPlotParallelCoordinates *) a0->native.GetPointer()
		);
		return;
	}
	Nan::ThrowError("Parameter mismatch");
}

void VtkChartParallelCoordinatesWrap::Update(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkChartParallelCoordinatesWrap *wrapper = ObjectWrap::Unwrap<VtkChartParallelCoordinatesWrap>(info.Holder());
	vtkChartParallelCoordinates *native = (vtkChartParallelCoordinates *)wrapper->native.GetPointer();
	if(info.Length() != 0)
	{
		Nan::ThrowError("Too many parameters.");
		return;
	}
	native->Update();
}

