/* this file has been autogenerated by vtkNodeJsWrap */
/* editing this might proof futile */

#define VTK_WRAPPING_CXX
#define VTK_STREAMS_FWD_ONLY
#include <nan.h>


#include "vtkPolyDataAlgorithmWrap.h"
#include "vtkEdgeCentersWrap.h"
#include "vtkObjectWrap.h"

using namespace v8;

extern Nan::Persistent<v8::Object> vtkNodeJsNoWrap;
Nan::Persistent<v8::Function> VtkEdgeCentersWrap::constructor;

VtkEdgeCentersWrap::VtkEdgeCentersWrap()
{ }

VtkEdgeCentersWrap::VtkEdgeCentersWrap(vtkSmartPointer<vtkEdgeCenters> _native)
{ native = _native; }

VtkEdgeCentersWrap::~VtkEdgeCentersWrap()
{ }

void VtkEdgeCentersWrap::Init(v8::Local<v8::Object> exports)
{
	Nan::HandleScope scope;

	v8::Local<v8::FunctionTemplate> tpl = Nan::New<v8::FunctionTemplate>(New);
	tpl->SetClassName(Nan::New("VtkEdgeCentersWrap").ToLocalChecked());
	tpl->InstanceTemplate()->SetInternalFieldCount(1);

	VtkObjectBaseWrap::InitTpl(tpl);
	VtkObjectWrap::InitTpl(tpl);
	VtkAlgorithmWrap::InitTpl(tpl);
	VtkPolyDataAlgorithmWrap::InitTpl(tpl);
	InitTpl(tpl);

	constructor.Reset( tpl->GetFunction() );

	exports->Set(Nan::New("vtkEdgeCenters").ToLocalChecked(),tpl->GetFunction());
	exports->Set(Nan::New("EdgeCenters").ToLocalChecked(),tpl->GetFunction());
}

void VtkEdgeCentersWrap::InitTpl(v8::Local<v8::FunctionTemplate> tpl)
{
	Nan::SetPrototypeMethod(tpl, "GetClassName", GetClassName);
	Nan::SetPrototypeMethod(tpl, "getClassName", GetClassName);

	Nan::SetPrototypeMethod(tpl, "GetVertexCells", GetVertexCells);
	Nan::SetPrototypeMethod(tpl, "getVertexCells", GetVertexCells);

	Nan::SetPrototypeMethod(tpl, "IsA", IsA);
	Nan::SetPrototypeMethod(tpl, "isA", IsA);

	Nan::SetPrototypeMethod(tpl, "NewInstance", NewInstance);
	Nan::SetPrototypeMethod(tpl, "newInstance", NewInstance);

	Nan::SetPrototypeMethod(tpl, "SafeDownCast", SafeDownCast);
	Nan::SetPrototypeMethod(tpl, "safeDownCast", SafeDownCast);

	Nan::SetPrototypeMethod(tpl, "SetVertexCells", SetVertexCells);
	Nan::SetPrototypeMethod(tpl, "setVertexCells", SetVertexCells);

	Nan::SetPrototypeMethod(tpl, "VertexCellsOff", VertexCellsOff);
	Nan::SetPrototypeMethod(tpl, "vertexCellsOff", VertexCellsOff);

	Nan::SetPrototypeMethod(tpl, "VertexCellsOn", VertexCellsOn);
	Nan::SetPrototypeMethod(tpl, "vertexCellsOn", VertexCellsOn);

}

void VtkEdgeCentersWrap::New(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	if(!info.IsConstructCall())
	{
		Nan::ThrowError("Constructor not called in a construct call.");
		return;
	}

	if(info.Length() == 0)
	{
		vtkSmartPointer<vtkEdgeCenters> native = vtkSmartPointer<vtkEdgeCenters>::New();
		VtkEdgeCentersWrap* obj = new VtkEdgeCentersWrap(native);		obj->Wrap(info.This());
	}
	else
	{
		Nan::Utf8String s(info[0]);
		if(info[0]->ToObject() != vtkNodeJsNoWrap )
			Nan::ThrowError("Parameter Error");
	}

	info.GetReturnValue().Set(info.This());
}

void VtkEdgeCentersWrap::GetClassName(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkEdgeCentersWrap *wrapper = ObjectWrap::Unwrap<VtkEdgeCentersWrap>(info.Holder());
	vtkEdgeCenters *native = (vtkEdgeCenters *)wrapper->native.GetPointer();
	char const * r;
	if(info.Length() != 0)
	{
		Nan::ThrowError("Too many parameters.");
		return;
	}
	r = native->GetClassName();
	info.GetReturnValue().Set(Nan::New(r).ToLocalChecked());
}

void VtkEdgeCentersWrap::GetVertexCells(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkEdgeCentersWrap *wrapper = ObjectWrap::Unwrap<VtkEdgeCentersWrap>(info.Holder());
	vtkEdgeCenters *native = (vtkEdgeCenters *)wrapper->native.GetPointer();
	int r;
	if(info.Length() != 0)
	{
		Nan::ThrowError("Too many parameters.");
		return;
	}
	r = native->GetVertexCells();
	info.GetReturnValue().Set(Nan::New(r));
}

void VtkEdgeCentersWrap::IsA(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkEdgeCentersWrap *wrapper = ObjectWrap::Unwrap<VtkEdgeCentersWrap>(info.Holder());
	vtkEdgeCenters *native = (vtkEdgeCenters *)wrapper->native.GetPointer();
	if(info.Length() > 0 && info[0]->IsInt32())
	{
		Nan::Utf8String a0(info[0]);
		int r;
		if(info.Length() != 1)
		{
			Nan::ThrowError("Too many parameters.");
			return;
		}
		r = native->IsA(
			*a0
		);
		info.GetReturnValue().Set(Nan::New(r));
		return;
	}
	Nan::ThrowError("Parameter mismatch");
}

void VtkEdgeCentersWrap::NewInstance(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkEdgeCentersWrap *wrapper = ObjectWrap::Unwrap<VtkEdgeCentersWrap>(info.Holder());
	vtkEdgeCenters *native = (vtkEdgeCenters *)wrapper->native.GetPointer();
	vtkEdgeCenters * r;
	if(info.Length() != 0)
	{
		Nan::ThrowError("Too many parameters.");
		return;
	}
	r = native->NewInstance();
	v8::Local<v8::Value> argv[1] =
		{ Nan::New(vtkNodeJsNoWrap) };
	v8::Local<v8::Function> cons =
		Nan::New<v8::Function>(VtkEdgeCentersWrap::constructor);
	v8::Local<v8::Object> wo = cons->NewInstance(1, argv);
	VtkEdgeCentersWrap *w = new VtkEdgeCentersWrap();
	w->native.TakeReference(r);
	w->Wrap(wo);
	info.GetReturnValue().Set(wo);
}

void VtkEdgeCentersWrap::SafeDownCast(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkEdgeCentersWrap *wrapper = ObjectWrap::Unwrap<VtkEdgeCentersWrap>(info.Holder());
	vtkEdgeCenters *native = (vtkEdgeCenters *)wrapper->native.GetPointer();
	if(info.Length() > 0 && info[0]->IsObject())
	{
		VtkObjectWrap *a0 = ObjectWrap::Unwrap<VtkObjectWrap>(info[0]->ToObject());
		vtkEdgeCenters * r;
		if(info.Length() != 1)
		{
			Nan::ThrowError("Too many parameters.");
			return;
		}
		r = native->SafeDownCast(
			(vtkObject *) a0->native.GetPointer()
		);
		v8::Local<v8::Value> argv[1] =
			{ Nan::New(vtkNodeJsNoWrap) };
		v8::Local<v8::Function> cons =
			Nan::New<v8::Function>(VtkEdgeCentersWrap::constructor);
		v8::Local<v8::Object> wo = cons->NewInstance(1, argv);
		VtkEdgeCentersWrap *w = new VtkEdgeCentersWrap();
		w->native.TakeReference(r);
		w->Wrap(wo);
		info.GetReturnValue().Set(wo);
		return;
	}
	Nan::ThrowError("Parameter mismatch");
}

void VtkEdgeCentersWrap::SetVertexCells(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkEdgeCentersWrap *wrapper = ObjectWrap::Unwrap<VtkEdgeCentersWrap>(info.Holder());
	vtkEdgeCenters *native = (vtkEdgeCenters *)wrapper->native.GetPointer();
	if(info.Length() > 0 && info[0]->IsInt32())
	{
		if(info.Length() != 1)
		{
			Nan::ThrowError("Too many parameters.");
			return;
		}
		native->SetVertexCells(
			info[0]->Int32Value()
		);
		return;
	}
	Nan::ThrowError("Parameter mismatch");
}

void VtkEdgeCentersWrap::VertexCellsOff(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkEdgeCentersWrap *wrapper = ObjectWrap::Unwrap<VtkEdgeCentersWrap>(info.Holder());
	vtkEdgeCenters *native = (vtkEdgeCenters *)wrapper->native.GetPointer();
	if(info.Length() != 0)
	{
		Nan::ThrowError("Too many parameters.");
		return;
	}
	native->VertexCellsOff();
}

void VtkEdgeCentersWrap::VertexCellsOn(const Nan::FunctionCallbackInfo<v8::Value>& info)
{
	VtkEdgeCentersWrap *wrapper = ObjectWrap::Unwrap<VtkEdgeCentersWrap>(info.Holder());
	vtkEdgeCenters *native = (vtkEdgeCenters *)wrapper->native.GetPointer();
	if(info.Length() != 0)
	{
		Nan::ThrowError("Too many parameters.");
		return;
	}
	native->VertexCellsOn();
}

