/* this file has been autogenerated by vtkNodeJsWrap */
/* editing this might proof futile */

#ifndef NATIVE_EXTENSION_VTK_VTKRIBLIGHTWRAP_H
#define NATIVE_EXTENSION_VTK_VTKRIBLIGHTWRAP_H

#include <nan.h>

#include <vtkSmartPointer.h>
#include <vtkRIBLight.h>

#include "vtkLightWrap.h"

class VtkRIBLightWrap : public VtkLightWrap
{
	public:
		using Nan::ObjectWrap::Wrap;
		static void Init(v8::Local<v8::Object> exports);
		static void InitTpl(v8::Local<v8::FunctionTemplate> tpl);

		VtkRIBLightWrap(vtkSmartPointer<vtkRIBLight>);
		VtkRIBLightWrap();
		~VtkRIBLightWrap( );
		static Nan::Persistent<v8::Function> constructor;

	private:
		static void New(const Nan::FunctionCallbackInfo<v8::Value>& info);

		static void GetClassName(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void GetShadows(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void IsA(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void NewInstance(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void Render(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SafeDownCast(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void SetShadows(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void ShadowsOff(const Nan::FunctionCallbackInfo<v8::Value>& info);
		static void ShadowsOn(const Nan::FunctionCallbackInfo<v8::Value>& info);
};

#endif
